'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
'
Namespace WSNavyUtilerias
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="Application", [Namespace]:="http://facturacion.finkok.com/utilities")>  _
    Partial Public Class UtilitiesSOAP
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private report_totalOperationCompleted As System.Threading.SendOrPostCallback
        
        Private get_moneda_usdOperationCompleted As System.Threading.SendOrPostCallback
        
        Private report_uuidOperationCompleted As System.Threading.SendOrPostCallback
        
        Private get_moneda_usd_by_dateOperationCompleted As System.Threading.SendOrPostCallback
        
        Private reset_tokenOperationCompleted As System.Threading.SendOrPostCallback
        
        Private get_xmlOperationCompleted As System.Threading.SendOrPostCallback
        
        Private add_tokenOperationCompleted As System.Threading.SendOrPostCallback
        
        Private report_creditOperationCompleted As System.Threading.SendOrPostCallback
        
        Private update_tokenOperationCompleted As System.Threading.SendOrPostCallback
        
        Private datetimeOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.FacturacionPersonal.My.MySettings.Default.FacturacionPersonal_WSNavyUtilerias_UtilitiesSOAP
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event report_totalCompleted As report_totalCompletedEventHandler
        
        '''<remarks/>
        Public Event get_moneda_usdCompleted As get_moneda_usdCompletedEventHandler
        
        '''<remarks/>
        Public Event report_uuidCompleted As report_uuidCompletedEventHandler
        
        '''<remarks/>
        Public Event get_moneda_usd_by_dateCompleted As get_moneda_usd_by_dateCompletedEventHandler
        
        '''<remarks/>
        Public Event reset_tokenCompleted As reset_tokenCompletedEventHandler
        
        '''<remarks/>
        Public Event get_xmlCompleted As get_xmlCompletedEventHandler
        
        '''<remarks/>
        Public Event add_tokenCompleted As add_tokenCompletedEventHandler
        
        '''<remarks/>
        Public Event report_creditCompleted As report_creditCompletedEventHandler
        
        '''<remarks/>
        Public Event update_tokenCompleted As update_tokenCompletedEventHandler
        
        '''<remarks/>
        Public Event datetimeCompleted As datetimeCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("report_total", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
        Public Function report_total(<System.Xml.Serialization.XmlElementAttribute("report_total", [Namespace]:="http://facturacion.finkok.com/utilities")> ByVal report_total1 As report_total) As <System.Xml.Serialization.XmlElementAttribute("report_totalResponse", [Namespace]:="http://facturacion.finkok.com/utilities")> report_totalResponse
            Dim results() As Object = Me.Invoke("report_total", New Object() {report_total1})
            Return CType(results(0),report_totalResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub report_totalAsync(ByVal report_total1 As report_total)
            Me.report_totalAsync(report_total1, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub report_totalAsync(ByVal report_total1 As report_total, ByVal userState As Object)
            If (Me.report_totalOperationCompleted Is Nothing) Then
                Me.report_totalOperationCompleted = AddressOf Me.Onreport_totalOperationCompleted
            End If
            Me.InvokeAsync("report_total", New Object() {report_total1}, Me.report_totalOperationCompleted, userState)
        End Sub
        
        Private Sub Onreport_totalOperationCompleted(ByVal arg As Object)
            If (Not (Me.report_totalCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent report_totalCompleted(Me, New report_totalCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("get_moneda_usd", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
        Public Function get_moneda_usd(<System.Xml.Serialization.XmlElementAttribute("get_moneda_usd", [Namespace]:="http://facturacion.finkok.com/utilities")> ByVal get_moneda_usd1 As get_moneda_usd) As <System.Xml.Serialization.XmlElementAttribute("get_moneda_usdResponse", [Namespace]:="http://facturacion.finkok.com/utilities")> get_moneda_usdResponse
            Dim results() As Object = Me.Invoke("get_moneda_usd", New Object() {get_moneda_usd1})
            Return CType(results(0),get_moneda_usdResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub get_moneda_usdAsync(ByVal get_moneda_usd1 As get_moneda_usd)
            Me.get_moneda_usdAsync(get_moneda_usd1, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub get_moneda_usdAsync(ByVal get_moneda_usd1 As get_moneda_usd, ByVal userState As Object)
            If (Me.get_moneda_usdOperationCompleted Is Nothing) Then
                Me.get_moneda_usdOperationCompleted = AddressOf Me.Onget_moneda_usdOperationCompleted
            End If
            Me.InvokeAsync("get_moneda_usd", New Object() {get_moneda_usd1}, Me.get_moneda_usdOperationCompleted, userState)
        End Sub
        
        Private Sub Onget_moneda_usdOperationCompleted(ByVal arg As Object)
            If (Not (Me.get_moneda_usdCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent get_moneda_usdCompleted(Me, New get_moneda_usdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("report_uuid", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
        Public Function report_uuid(<System.Xml.Serialization.XmlElementAttribute("report_uuid", [Namespace]:="http://facturacion.finkok.com/utilities")> ByVal report_uuid1 As report_uuid) As <System.Xml.Serialization.XmlElementAttribute("report_uuidResponse", [Namespace]:="http://facturacion.finkok.com/utilities")> report_uuidResponse
            Dim results() As Object = Me.Invoke("report_uuid", New Object() {report_uuid1})
            Return CType(results(0),report_uuidResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub report_uuidAsync(ByVal report_uuid1 As report_uuid)
            Me.report_uuidAsync(report_uuid1, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub report_uuidAsync(ByVal report_uuid1 As report_uuid, ByVal userState As Object)
            If (Me.report_uuidOperationCompleted Is Nothing) Then
                Me.report_uuidOperationCompleted = AddressOf Me.Onreport_uuidOperationCompleted
            End If
            Me.InvokeAsync("report_uuid", New Object() {report_uuid1}, Me.report_uuidOperationCompleted, userState)
        End Sub
        
        Private Sub Onreport_uuidOperationCompleted(ByVal arg As Object)
            If (Not (Me.report_uuidCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent report_uuidCompleted(Me, New report_uuidCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("get_moneda_usd_by_date", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
        Public Function get_moneda_usd_by_date(<System.Xml.Serialization.XmlElementAttribute("get_moneda_usd_by_date", [Namespace]:="http://facturacion.finkok.com/utilities")> ByVal get_moneda_usd_by_date1 As get_moneda_usd_by_date) As <System.Xml.Serialization.XmlElementAttribute("get_moneda_usd_by_dateResponse", [Namespace]:="http://facturacion.finkok.com/utilities")> get_moneda_usd_by_dateResponse
            Dim results() As Object = Me.Invoke("get_moneda_usd_by_date", New Object() {get_moneda_usd_by_date1})
            Return CType(results(0),get_moneda_usd_by_dateResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub get_moneda_usd_by_dateAsync(ByVal get_moneda_usd_by_date1 As get_moneda_usd_by_date)
            Me.get_moneda_usd_by_dateAsync(get_moneda_usd_by_date1, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub get_moneda_usd_by_dateAsync(ByVal get_moneda_usd_by_date1 As get_moneda_usd_by_date, ByVal userState As Object)
            If (Me.get_moneda_usd_by_dateOperationCompleted Is Nothing) Then
                Me.get_moneda_usd_by_dateOperationCompleted = AddressOf Me.Onget_moneda_usd_by_dateOperationCompleted
            End If
            Me.InvokeAsync("get_moneda_usd_by_date", New Object() {get_moneda_usd_by_date1}, Me.get_moneda_usd_by_dateOperationCompleted, userState)
        End Sub
        
        Private Sub Onget_moneda_usd_by_dateOperationCompleted(ByVal arg As Object)
            If (Not (Me.get_moneda_usd_by_dateCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent get_moneda_usd_by_dateCompleted(Me, New get_moneda_usd_by_dateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("reset_token", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
        Public Function reset_token(<System.Xml.Serialization.XmlElementAttribute("reset_token", [Namespace]:="http://facturacion.finkok.com/utilities")> ByVal reset_token1 As reset_token) As <System.Xml.Serialization.XmlElementAttribute("reset_tokenResponse", [Namespace]:="http://facturacion.finkok.com/utilities")> reset_tokenResponse
            Dim results() As Object = Me.Invoke("reset_token", New Object() {reset_token1})
            Return CType(results(0),reset_tokenResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub reset_tokenAsync(ByVal reset_token1 As reset_token)
            Me.reset_tokenAsync(reset_token1, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub reset_tokenAsync(ByVal reset_token1 As reset_token, ByVal userState As Object)
            If (Me.reset_tokenOperationCompleted Is Nothing) Then
                Me.reset_tokenOperationCompleted = AddressOf Me.Onreset_tokenOperationCompleted
            End If
            Me.InvokeAsync("reset_token", New Object() {reset_token1}, Me.reset_tokenOperationCompleted, userState)
        End Sub
        
        Private Sub Onreset_tokenOperationCompleted(ByVal arg As Object)
            If (Not (Me.reset_tokenCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent reset_tokenCompleted(Me, New reset_tokenCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("get_xml", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
        Public Function get_xml(<System.Xml.Serialization.XmlElementAttribute("get_xml", [Namespace]:="http://facturacion.finkok.com/utilities")> ByVal get_xml1 As get_xml) As <System.Xml.Serialization.XmlElementAttribute("get_xmlResponse", [Namespace]:="http://facturacion.finkok.com/utilities")> get_xmlResponse
            Dim results() As Object = Me.Invoke("get_xml", New Object() {get_xml1})
            Return CType(results(0),get_xmlResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub get_xmlAsync(ByVal get_xml1 As get_xml)
            Me.get_xmlAsync(get_xml1, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub get_xmlAsync(ByVal get_xml1 As get_xml, ByVal userState As Object)
            If (Me.get_xmlOperationCompleted Is Nothing) Then
                Me.get_xmlOperationCompleted = AddressOf Me.Onget_xmlOperationCompleted
            End If
            Me.InvokeAsync("get_xml", New Object() {get_xml1}, Me.get_xmlOperationCompleted, userState)
        End Sub
        
        Private Sub Onget_xmlOperationCompleted(ByVal arg As Object)
            If (Not (Me.get_xmlCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent get_xmlCompleted(Me, New get_xmlCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("add_token", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
        Public Function add_token(<System.Xml.Serialization.XmlElementAttribute("add_token", [Namespace]:="http://facturacion.finkok.com/utilities")> ByVal add_token1 As add_token) As <System.Xml.Serialization.XmlElementAttribute("add_tokenResponse", [Namespace]:="http://facturacion.finkok.com/utilities")> add_tokenResponse
            Dim results() As Object = Me.Invoke("add_token", New Object() {add_token1})
            Return CType(results(0),add_tokenResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub add_tokenAsync(ByVal add_token1 As add_token)
            Me.add_tokenAsync(add_token1, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub add_tokenAsync(ByVal add_token1 As add_token, ByVal userState As Object)
            If (Me.add_tokenOperationCompleted Is Nothing) Then
                Me.add_tokenOperationCompleted = AddressOf Me.Onadd_tokenOperationCompleted
            End If
            Me.InvokeAsync("add_token", New Object() {add_token1}, Me.add_tokenOperationCompleted, userState)
        End Sub
        
        Private Sub Onadd_tokenOperationCompleted(ByVal arg As Object)
            If (Not (Me.add_tokenCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent add_tokenCompleted(Me, New add_tokenCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("report_credit", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
        Public Function report_credit(<System.Xml.Serialization.XmlElementAttribute("report_credit", [Namespace]:="http://facturacion.finkok.com/utilities")> ByVal report_credit1 As report_credit) As <System.Xml.Serialization.XmlElementAttribute("report_creditResponse", [Namespace]:="http://facturacion.finkok.com/utilities")> report_creditResponse
            Dim results() As Object = Me.Invoke("report_credit", New Object() {report_credit1})
            Return CType(results(0),report_creditResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub report_creditAsync(ByVal report_credit1 As report_credit)
            Me.report_creditAsync(report_credit1, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub report_creditAsync(ByVal report_credit1 As report_credit, ByVal userState As Object)
            If (Me.report_creditOperationCompleted Is Nothing) Then
                Me.report_creditOperationCompleted = AddressOf Me.Onreport_creditOperationCompleted
            End If
            Me.InvokeAsync("report_credit", New Object() {report_credit1}, Me.report_creditOperationCompleted, userState)
        End Sub
        
        Private Sub Onreport_creditOperationCompleted(ByVal arg As Object)
            If (Not (Me.report_creditCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent report_creditCompleted(Me, New report_creditCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("update_token", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
        Public Function update_token(<System.Xml.Serialization.XmlElementAttribute("update_token", [Namespace]:="http://facturacion.finkok.com/utilities")> ByVal update_token1 As update_token) As <System.Xml.Serialization.XmlElementAttribute("update_tokenResponse", [Namespace]:="http://facturacion.finkok.com/utilities")> update_tokenResponse
            Dim results() As Object = Me.Invoke("update_token", New Object() {update_token1})
            Return CType(results(0),update_tokenResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub update_tokenAsync(ByVal update_token1 As update_token)
            Me.update_tokenAsync(update_token1, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub update_tokenAsync(ByVal update_token1 As update_token, ByVal userState As Object)
            If (Me.update_tokenOperationCompleted Is Nothing) Then
                Me.update_tokenOperationCompleted = AddressOf Me.Onupdate_tokenOperationCompleted
            End If
            Me.InvokeAsync("update_token", New Object() {update_token1}, Me.update_tokenOperationCompleted, userState)
        End Sub
        
        Private Sub Onupdate_tokenOperationCompleted(ByVal arg As Object)
            If (Not (Me.update_tokenCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent update_tokenCompleted(Me, New update_tokenCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("datetime", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
        Public Function datetime(<System.Xml.Serialization.XmlElementAttribute("datetime", [Namespace]:="http://facturacion.finkok.com/utilities")> ByVal datetime1 As datetime) As <System.Xml.Serialization.XmlElementAttribute("datetimeResponse", [Namespace]:="http://facturacion.finkok.com/utilities")> datetimeResponse
            Dim results() As Object = Me.Invoke("datetime", New Object() {datetime1})
            Return CType(results(0),datetimeResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub datetimeAsync(ByVal datetime1 As datetime)
            Me.datetimeAsync(datetime1, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub datetimeAsync(ByVal datetime1 As datetime, ByVal userState As Object)
            If (Me.datetimeOperationCompleted Is Nothing) Then
                Me.datetimeOperationCompleted = AddressOf Me.OndatetimeOperationCompleted
            End If
            Me.InvokeAsync("datetime", New Object() {datetime1}, Me.datetimeOperationCompleted, userState)
        End Sub
        
        Private Sub OndatetimeOperationCompleted(ByVal arg As Object)
            If (Not (Me.datetimeCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent datetimeCompleted(Me, New datetimeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://facturacion.finkok.com/utilities")>  _
    Partial Public Class report_total
        
        Private usernameField As String
        
        Private passwordField As String
        
        Private taxpayer_idField As String
        
        Private date_fromField As Date
        
        Private date_toField As Date
        
        Private invoice_typeField As String
        
        '''<remarks/>
        Public Property username() As String
            Get
                Return Me.usernameField
            End Get
            Set
                Me.usernameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property password() As String
            Get
                Return Me.passwordField
            End Get
            Set
                Me.passwordField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property taxpayer_id() As String
            Get
                Return Me.taxpayer_idField
            End Get
            Set
                Me.taxpayer_idField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property date_from() As Date
            Get
                Return Me.date_fromField
            End Get
            Set
                Me.date_fromField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property date_to() As Date
            Get
                Return Me.date_toField
            End Get
            Set
                Me.date_toField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property invoice_type() As String
            Get
                Return Me.invoice_typeField
            End Get
            Set
                Me.invoice_typeField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="apps.services.soap.core.views")>  _
    Partial Public Class DateResult
        
        Private errorField As String
        
        Private datetimeField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property [error]() As String
            Get
                Return Me.errorField
            End Get
            Set
                Me.errorField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property datetime() As String
            Get
                Return Me.datetimeField
            End Get
            Set
                Me.datetimeField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://facturacion.finkok.com/utilities")>  _
    Partial Public Class datetimeResponse
        
        Private datetimeResultField As DateResult
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property datetimeResult() As DateResult
            Get
                Return Me.datetimeResultField
            End Get
            Set
                Me.datetimeResultField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://facturacion.finkok.com/utilities")>  _
    Partial Public Class datetime
        
        Private usernameField As String
        
        Private passwordField As String
        
        Private zipcodeField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property username() As String
            Get
                Return Me.usernameField
            End Get
            Set
                Me.usernameField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property password() As String
            Get
                Return Me.passwordField
            End Get
            Set
                Me.passwordField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property zipcode() As String
            Get
                Return Me.zipcodeField
            End Get
            Set
                Me.zipcodeField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://facturacion.finkok.com/utilities")>  _
    Partial Public Class update_tokenResponse
        
        Private update_tokenResultField As ResponseToken
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property update_tokenResult() As ResponseToken
            Get
                Return Me.update_tokenResultField
            End Get
            Set
                Me.update_tokenResultField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="apps.services.soap.core.views")>  _
    Partial Public Class ResponseToken
        
        Private usernameField As String
        
        Private statusField As System.Nullable(Of Boolean)
        
        Private statusFieldSpecified As Boolean
        
        Private nameField As String
        
        Private successField As System.Nullable(Of Boolean)
        
        Private successFieldSpecified As Boolean
        
        Private tokenField As String
        
        Private messageField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property username() As String
            Get
                Return Me.usernameField
            End Get
            Set
                Me.usernameField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property status() As System.Nullable(Of Boolean)
            Get
                Return Me.statusField
            End Get
            Set
                Me.statusField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property statusSpecified() As Boolean
            Get
                Return Me.statusFieldSpecified
            End Get
            Set
                Me.statusFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property name() As String
            Get
                Return Me.nameField
            End Get
            Set
                Me.nameField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property success() As System.Nullable(Of Boolean)
            Get
                Return Me.successField
            End Get
            Set
                Me.successField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property successSpecified() As Boolean
            Get
                Return Me.successFieldSpecified
            End Get
            Set
                Me.successFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property token() As String
            Get
                Return Me.tokenField
            End Get
            Set
                Me.tokenField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property message() As String
            Get
                Return Me.messageField
            End Get
            Set
                Me.messageField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://facturacion.finkok.com/utilities")>  _
    Partial Public Class update_token
        
        Private usernameField As String
        
        Private passwordField As String
        
        Private tokenField As String
        
        Private statusField As System.Nullable(Of Boolean)
        
        Private statusFieldSpecified As Boolean
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property username() As String
            Get
                Return Me.usernameField
            End Get
            Set
                Me.usernameField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property password() As String
            Get
                Return Me.passwordField
            End Get
            Set
                Me.passwordField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property token() As String
            Get
                Return Me.tokenField
            End Get
            Set
                Me.tokenField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property status() As System.Nullable(Of Boolean)
            Get
                Return Me.statusField
            End Get
            Set
                Me.statusField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property statusSpecified() As Boolean
            Get
                Return Me.statusFieldSpecified
            End Get
            Set
                Me.statusFieldSpecified = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="apps.services.soap.core.views")>  _
    Partial Public Class ReportTotalCredit
        
        Private taxpayer_idField As String
        
        Private creditField As String
        
        Private dateField As System.Nullable(Of Date)
        
        Private dateFieldSpecified As Boolean
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property taxpayer_id() As String
            Get
                Return Me.taxpayer_idField
            End Get
            Set
                Me.taxpayer_idField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="integer", IsNullable:=true)>  _
        Public Property credit() As String
            Get
                Return Me.creditField
            End Get
            Set
                Me.creditField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property [date]() As System.Nullable(Of Date)
            Get
                Return Me.dateField
            End Get
            Set
                Me.dateField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property dateSpecified() As Boolean
            Get
                Return Me.dateFieldSpecified
            End Get
            Set
                Me.dateFieldSpecified = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="apps.services.soap.core.views")>  _
    Partial Public Class ReportTotalCreditResult
        
        Private resultField() As ReportTotalCredit
        
        Private errorField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(IsNullable:=true)>  _
        Public Property result() As ReportTotalCredit()
            Get
                Return Me.resultField
            End Get
            Set
                Me.resultField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property [error]() As String
            Get
                Return Me.errorField
            End Get
            Set
                Me.errorField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://facturacion.finkok.com/utilities")>  _
    Partial Public Class report_creditResponse
        
        Private report_creditResultField As ReportTotalCreditResult
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property report_creditResult() As ReportTotalCreditResult
            Get
                Return Me.report_creditResultField
            End Get
            Set
                Me.report_creditResultField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://facturacion.finkok.com/utilities")>  _
    Partial Public Class report_credit
        
        Private usernameField As String
        
        Private passwordField As String
        
        Private taxpayer_idField As String
        
        '''<remarks/>
        Public Property username() As String
            Get
                Return Me.usernameField
            End Get
            Set
                Me.usernameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property password() As String
            Get
                Return Me.passwordField
            End Get
            Set
                Me.passwordField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property taxpayer_id() As String
            Get
                Return Me.taxpayer_idField
            End Get
            Set
                Me.taxpayer_idField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://facturacion.finkok.com/utilities")>  _
    Partial Public Class add_tokenResponse
        
        Private add_tokenResultField As ResponseToken
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property add_tokenResult() As ResponseToken
            Get
                Return Me.add_tokenResultField
            End Get
            Set
                Me.add_tokenResultField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://facturacion.finkok.com/utilities")>  _
    Partial Public Class add_token
        
        Private usernameField As String
        
        Private passwordField As String
        
        Private nameField As String
        
        Private token_usernameField As String
        
        Private taxpayer_idField As String
        
        Private statusField As System.Nullable(Of Boolean)
        
        Private statusFieldSpecified As Boolean
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property username() As String
            Get
                Return Me.usernameField
            End Get
            Set
                Me.usernameField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property password() As String
            Get
                Return Me.passwordField
            End Get
            Set
                Me.passwordField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property name() As String
            Get
                Return Me.nameField
            End Get
            Set
                Me.nameField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property token_username() As String
            Get
                Return Me.token_usernameField
            End Get
            Set
                Me.token_usernameField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property taxpayer_id() As String
            Get
                Return Me.taxpayer_idField
            End Get
            Set
                Me.taxpayer_idField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property status() As System.Nullable(Of Boolean)
            Get
                Return Me.statusField
            End Get
            Set
                Me.statusField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property statusSpecified() As Boolean
            Get
                Return Me.statusFieldSpecified
            End Get
            Set
                Me.statusFieldSpecified = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="apps.services.soap.core.views")>  _
    Partial Public Class XMLResult
        
        Private xmlField As String
        
        Private errorField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property xml() As String
            Get
                Return Me.xmlField
            End Get
            Set
                Me.xmlField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property [error]() As String
            Get
                Return Me.errorField
            End Get
            Set
                Me.errorField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://facturacion.finkok.com/utilities")>  _
    Partial Public Class get_xmlResponse
        
        Private get_xmlResultField As XMLResult
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property get_xmlResult() As XMLResult
            Get
                Return Me.get_xmlResultField
            End Get
            Set
                Me.get_xmlResultField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://facturacion.finkok.com/utilities")>  _
    Partial Public Class get_xml
        
        Private usernameField As String
        
        Private passwordField As String
        
        Private uuidField As String
        
        Private taxpayer_idField As String
        
        Private invoice_typeField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property username() As String
            Get
                Return Me.usernameField
            End Get
            Set
                Me.usernameField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property password() As String
            Get
                Return Me.passwordField
            End Get
            Set
                Me.passwordField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property uuid() As String
            Get
                Return Me.uuidField
            End Get
            Set
                Me.uuidField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property taxpayer_id() As String
            Get
                Return Me.taxpayer_idField
            End Get
            Set
                Me.taxpayer_idField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property invoice_type() As String
            Get
                Return Me.invoice_typeField
            End Get
            Set
                Me.invoice_typeField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://facturacion.finkok.com/utilities")>  _
    Partial Public Class reset_tokenResponse
        
        Private reset_tokenResultField As ResponseToken
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property reset_tokenResult() As ResponseToken
            Get
                Return Me.reset_tokenResultField
            End Get
            Set
                Me.reset_tokenResultField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://facturacion.finkok.com/utilities")>  _
    Partial Public Class reset_token
        
        Private usernameField As String
        
        Private passwordField As String
        
        Private tokenField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property username() As String
            Get
                Return Me.usernameField
            End Get
            Set
                Me.usernameField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property password() As String
            Get
                Return Me.passwordField
            End Get
            Set
                Me.passwordField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property token() As String
            Get
                Return Me.tokenField
            End Get
            Set
                Me.tokenField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://facturacion.finkok.com/utilities")>  _
    Partial Public Class get_moneda_usd_by_dateResponse
        
        Private get_moneda_usd_by_dateResultField As MonedaResult
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property get_moneda_usd_by_dateResult() As MonedaResult
            Get
                Return Me.get_moneda_usd_by_dateResultField
            End Get
            Set
                Me.get_moneda_usd_by_dateResultField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="apps.services.soap.core.views")>  _
    Partial Public Class MonedaResult
        
        Private monedaField As String
        
        Private errorField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property moneda() As String
            Get
                Return Me.monedaField
            End Get
            Set
                Me.monedaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property [error]() As String
            Get
                Return Me.errorField
            End Get
            Set
                Me.errorField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://facturacion.finkok.com/utilities")>  _
    Partial Public Class get_moneda_usd_by_date
        
        Private usernameField As String
        
        Private passwordField As String
        
        Private dateField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property username() As String
            Get
                Return Me.usernameField
            End Get
            Set
                Me.usernameField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property password() As String
            Get
                Return Me.passwordField
            End Get
            Set
                Me.passwordField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property [date]() As String
            Get
                Return Me.dateField
            End Get
            Set
                Me.dateField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="apps.services.soap.core.views")>  _
    Partial Public Class ReportUUID
        
        Private uuidField As String
        
        Private invoice_typeField As String
        
        Private taxpayer_idField As String
        
        Private rtaxpayer_idField As String
        
        Private complementsField As String
        
        Private dateField As System.Nullable(Of Date)
        
        Private dateFieldSpecified As Boolean
        
        Private totalField As System.Nullable(Of Single)
        
        Private totalFieldSpecified As Boolean
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property uuid() As String
            Get
                Return Me.uuidField
            End Get
            Set
                Me.uuidField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property invoice_type() As String
            Get
                Return Me.invoice_typeField
            End Get
            Set
                Me.invoice_typeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property taxpayer_id() As String
            Get
                Return Me.taxpayer_idField
            End Get
            Set
                Me.taxpayer_idField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property rtaxpayer_id() As String
            Get
                Return Me.rtaxpayer_idField
            End Get
            Set
                Me.rtaxpayer_idField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property complements() As String
            Get
                Return Me.complementsField
            End Get
            Set
                Me.complementsField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property [date]() As System.Nullable(Of Date)
            Get
                Return Me.dateField
            End Get
            Set
                Me.dateField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property dateSpecified() As Boolean
            Get
                Return Me.dateFieldSpecified
            End Get
            Set
                Me.dateFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property total() As System.Nullable(Of Single)
            Get
                Return Me.totalField
            End Get
            Set
                Me.totalField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property totalSpecified() As Boolean
            Get
                Return Me.totalFieldSpecified
            End Get
            Set
                Me.totalFieldSpecified = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="apps.services.soap.core.views")>  _
    Partial Public Class ReportUUIDResult
        
        Private invoicesField() As ReportUUID
        
        Private errorField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(IsNullable:=true)>  _
        Public Property invoices() As ReportUUID()
            Get
                Return Me.invoicesField
            End Get
            Set
                Me.invoicesField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property [error]() As String
            Get
                Return Me.errorField
            End Get
            Set
                Me.errorField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://facturacion.finkok.com/utilities")>  _
    Partial Public Class report_uuidResponse
        
        Private report_uuidResultField As ReportUUIDResult
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property report_uuidResult() As ReportUUIDResult
            Get
                Return Me.report_uuidResultField
            End Get
            Set
                Me.report_uuidResultField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://facturacion.finkok.com/utilities")>  _
    Partial Public Class report_uuid
        
        Private usernameField As String
        
        Private passwordField As String
        
        Private taxpayer_idField As String
        
        Private date_fromField As Date
        
        Private date_toField As Date
        
        Private invoice_typeField As String
        
        '''<remarks/>
        Public Property username() As String
            Get
                Return Me.usernameField
            End Get
            Set
                Me.usernameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property password() As String
            Get
                Return Me.passwordField
            End Get
            Set
                Me.passwordField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property taxpayer_id() As String
            Get
                Return Me.taxpayer_idField
            End Get
            Set
                Me.taxpayer_idField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property date_from() As Date
            Get
                Return Me.date_fromField
            End Get
            Set
                Me.date_fromField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property date_to() As Date
            Get
                Return Me.date_toField
            End Get
            Set
                Me.date_toField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property invoice_type() As String
            Get
                Return Me.invoice_typeField
            End Get
            Set
                Me.invoice_typeField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://facturacion.finkok.com/utilities")>  _
    Partial Public Class get_moneda_usdResponse
        
        Private get_moneda_usdResultField As MonedaResult
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property get_moneda_usdResult() As MonedaResult
            Get
                Return Me.get_moneda_usdResultField
            End Get
            Set
                Me.get_moneda_usdResultField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://facturacion.finkok.com/utilities")>  _
    Partial Public Class get_moneda_usd
        
        Private usernameField As String
        
        Private passwordField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property username() As String
            Get
                Return Me.usernameField
            End Get
            Set
                Me.usernameField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property password() As String
            Get
                Return Me.passwordField
            End Get
            Set
                Me.passwordField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="apps.services.soap.core.views")>  _
    Partial Public Class ReportTotal
        
        Private totalField As String
        
        Private taxpayer_idField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="integer", IsNullable:=true)>  _
        Public Property total() As String
            Get
                Return Me.totalField
            End Get
            Set
                Me.totalField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property taxpayer_id() As String
            Get
                Return Me.taxpayer_idField
            End Get
            Set
                Me.taxpayer_idField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="apps.services.soap.core.views")>  _
    Partial Public Class ReportTotalResult
        
        Private resultField() As ReportTotal
        
        Private errorField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(IsNullable:=true)>  _
        Public Property result() As ReportTotal()
            Get
                Return Me.resultField
            End Get
            Set
                Me.resultField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property [error]() As String
            Get
                Return Me.errorField
            End Get
            Set
                Me.errorField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://facturacion.finkok.com/utilities")>  _
    Partial Public Class report_totalResponse
        
        Private report_totalResultField As ReportTotalResult
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property report_totalResult() As ReportTotalResult
            Get
                Return Me.report_totalResultField
            End Get
            Set
                Me.report_totalResultField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")>  _
    Public Delegate Sub report_totalCompletedEventHandler(ByVal sender As Object, ByVal e As report_totalCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class report_totalCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As report_totalResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),report_totalResponse)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")>  _
    Public Delegate Sub get_moneda_usdCompletedEventHandler(ByVal sender As Object, ByVal e As get_moneda_usdCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class get_moneda_usdCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As get_moneda_usdResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),get_moneda_usdResponse)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")>  _
    Public Delegate Sub report_uuidCompletedEventHandler(ByVal sender As Object, ByVal e As report_uuidCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class report_uuidCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As report_uuidResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),report_uuidResponse)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")>  _
    Public Delegate Sub get_moneda_usd_by_dateCompletedEventHandler(ByVal sender As Object, ByVal e As get_moneda_usd_by_dateCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class get_moneda_usd_by_dateCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As get_moneda_usd_by_dateResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),get_moneda_usd_by_dateResponse)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")>  _
    Public Delegate Sub reset_tokenCompletedEventHandler(ByVal sender As Object, ByVal e As reset_tokenCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class reset_tokenCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As reset_tokenResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),reset_tokenResponse)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")>  _
    Public Delegate Sub get_xmlCompletedEventHandler(ByVal sender As Object, ByVal e As get_xmlCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class get_xmlCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As get_xmlResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),get_xmlResponse)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")>  _
    Public Delegate Sub add_tokenCompletedEventHandler(ByVal sender As Object, ByVal e As add_tokenCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class add_tokenCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As add_tokenResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),add_tokenResponse)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")>  _
    Public Delegate Sub report_creditCompletedEventHandler(ByVal sender As Object, ByVal e As report_creditCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class report_creditCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As report_creditResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),report_creditResponse)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")>  _
    Public Delegate Sub update_tokenCompletedEventHandler(ByVal sender As Object, ByVal e As update_tokenCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class update_tokenCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As update_tokenResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),update_tokenResponse)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")>  _
    Public Delegate Sub datetimeCompletedEventHandler(ByVal sender As Object, ByVal e As datetimeCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class datetimeCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As datetimeResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),datetimeResponse)
            End Get
        End Property
    End Class
End Namespace
